version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "35081:9000"
    environment:
      - PYTHONUNBUFFERED=1
      - MOE_SEARXNG_ENDPOINT=${MOE_SEARXNG_ENDPOINT}
    networks:
      - searxng
  
networks:
  searxng:
    external: true