version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "35081:9000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1